parser: babel-eslint
env:
  browser: true
  node: true
  es6: true
parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    jsx: true
plugins:
  - react
  - prettier
extends:
  - airbnb
  - prettier
rules:
  no-console: 0
  import/no-extraneous-dependencies:
    - error
    - devDependencies: true