parser: babel-eslint
env:
  browser: true
  node: true
  es6: true
parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    jsx: true
plugins:
  - flowtype
extends:
  - airbnb
  - plugin:flowtype/recommended
  - prettier
  - prettier/flowtype
  - prettier/react
settings:
  flowtype:
    onlyFilesWithFlowAnnotation: true
rules:
  no-console: 0
  import/no-extraneous-dependencies:
    - error
    - devDependencies: true
  jsx-a11y/no-static-element-interactions: 0
  flowtype/no-types-missing-file-annotation: 0
